version: '3.8' # Версия формата

services:
  main-site:
    image: ghcr.io/alex5sd/dombay-site:latest # Напиши тут свой логин вручную
    ports:
      - "8081:80"


  # Резервная копия сайта
  backup-site:
    image: ghcr.io/alex5sd/dombay-site:latest
    ports:
      - "8082:80" # Он будет доступен на порту 8082
