name: Docker Compose Master

on: [push]

jobs:
  orchestrate:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Login to Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Dual Tag
        run: |
          # 1. Создаем теги
          TAG=$(date +%Y%m%d-%H%M)
          IMAGE_DATE=ghcr.io/${{ github.repository_owner }}/dombay-site:$TAG
          IMAGE_LATEST=ghcr.io/${{ github.repository_owner }}/dombay-site:latest
          
          # 2. Собираем образ и даем ему сразу два имени
          docker build -t $IMAGE_DATE -t $IMAGE_LATEST .
          
          # 3. Пушим оба
          docker push $IMAGE_DATE
          docker push $IMAGE_LATEST

      - name: Run Orchestration
        run: |
          # Запускаем наш файл из корня проекта
          docker compose up -d
          
          # Даем 5 секунд проснуться
          sleep 5
          
          echo "--- ПРОВЕРКА ПОРТА 8081 ---"
          curl localhost:8081 | grep "поход"
          
          echo "--- ПРОВЕРКА ПОРТА 8082 ---"
          curl localhost:8082 | grep "поход"

      - name: Show Containers List
        run: docker ps
