name: Linux Learning Lab
on: [push]

jobs:
  terminal-basics:
    runs-on: ubuntu-latest
    steps:
      - name: Navigation Commands
        run: |
          echo "1. Кто залогинен в системе?"
          whoami
          
          echo "2. В какой папке я сейчас нахожусь?"
          pwd
          
          echo "3. Посмотри на 'корень' всей системы (главный склад)"
          ls /
                    echo "4. Создаем пустой файл"
          touch secret_note.txt
          
          echo "5. Записываем текст в файл"
          echo "Домбай прекрасен!" > note.txt
          
          echo "6. Дописываем текст в конец (не стирая старый)"
          echo "И Эльбрус тоже." >> note.txt
          
          echo "7. Читаем, что получилось"
          cat note.txt

